### ISSUE TITLE
a suggestion

### ISSUE THREAD

**Issue by scottocs** [EverythingMe/overscroll-decor#10]
your design is nice for my android app,but with the overscroll animation,i can't set my own loading gif logo,and can't find a chance to pull new data.

**Comment by d4vidi** [comment]
It is possible that the over-scroll doesn't work well out of the box with Google's "pull to refresh" feature.
My suggestion it in this case is to try this out:
Write your own custom 'adapter' (inherit an existing one) -- see [https://github.com/EverythingMe/overscroll-decor#advanced-usage](Advanced Usage] for details. Use it to completely override `isInAbsoluteStart` so it would always return 'false' - thus never fighting over control with the Google effect...
