### ISSUE TITLE
NestedScrollView

### ISSUE THREAD

**Issue by kekedaine** [EverythingMe/overscroll-decor#12]
Please make code work for NestedScrollView.

**Comment by d4vidi** [comment]
Will do. Thanks!

**Comment by zanderisrael** [comment]
up!

**Comment by artiestie** [comment]
Hey could you possibly set milestones to how far you've gone with this, and/or what problems you're facing?

**Comment by denisroyz** [comment]
To use this lib with NestedScrollView add such class to your project:

https://gist.github.com/denisroyz/81b8642115517229ef3969dfd4fa6947

And use it with: 

```
NestedScrollView nestedScrollView = (NestedScrollView ) findViewById(R.id.nested_scroll_view );
new VerticalOverScrollBounceEffectDecorator(new NestedScrollViewOverScrollDecorAdapter(nestedScrollView ));

```

**Comment by bhargavms** [comment]
Not working this isnt springing back :(

**Comment by d4vidi** [comment]
@denisroyz implementation seems a bit naive. Are you sure this works well?

**Comment by denisroyz** [comment]
@d4vidi i am sure it works with NestedScrollView in my project without issues.
But i can not be sure it works well in all situations.
I'v just took author's HorizontalScrollViewOverScrollDecorAdapter suorces, and switched them to NestedScrollView.

**Comment by bhargavms** [comment]
yep this is working, just need to do the set up in `onCreate()` (i.e before the view are drawn)

**Comment by d4vidi** [comment]
I would highly appreciate a PR: framework adapter as described + dedicated fragment in example-project 🙏

**Comment by bhargavms** [comment]
@d4vidi I've given a PR, will update it tomorrow with a dedicated fragment in example

**Comment by d4vidi** [comment]
@bhargavms exciting, tnx! as for fling - what exactly are you referring to? are you trying to implement the core overscroll-by-fling feature?

**Comment by bhargavms** [comment]
@d4vidi yes

**Comment by d4vidi** [comment]
In any case, I would much rather separate NestedScrollView from this feature so I could merge-in via a specific PR.

**Comment by bhargavms** [comment]
@d4vidi both nestedscrollviews and recyclerviews implement ScrollingViews dont they?

**Comment by bhargavms** [comment]
@d4vidi right now I'm stuck here, I have the velocity of the fling when the fling animation hits the absolute start/end, now how do I determine the duration and displacement to apply for the BounceInState animation?

**Comment by d4vidi** [comment]
This is identical to creating the 'slow-down animation' on the bounce-back state: when user's finger leaves the screen, the bounce-back animation first triggers a slow-down animation in the in-drag-direction (in case velocity > 0). Only once the slow-down is over, does it issue the bounce-back animation in the opposite direction. Your case is exactly the same; Here's the ref: https://github.com/EverythingMe/overscroll-decor/blob/master/liboverscroll/src/main/java/me/everything/android/ui/overscroll/OverScrollBounceEffectDecoratorBase.java#L391

**Comment by 2hamed** [comment]
Hi, 
Any update on this?

**Comment by viestursGr** [comment]
I am interested in update too!

**Comment by d4vidi** [comment]
I've pushed in a demo yesterday for NestedScrollView usage in example app.
As for fling support - won't seems to come anytime soon.

**Comment by Larnoo** [comment]
Hi, NestedScrollView can't scroll at demo. Android Api is 19.
When NestedScrollView has a sub-child(RecyclerView), NestedScrollView can't overscroll correctly. @d4vidi @bhargavms
