### ISSUE TITLE
MotionEvent.getHistorySize always return 0

### ISSUE THREAD

**Issue by yiranshaxiao** [EverythingMe/overscroll-decor#13]
MotionEvent.getHistorySize always return 0 on my device.
I found no solution on stackoverflow :(

```
Xperia Z
Android 5.1.1
CyanogenMod 12.1-20160316-NIGHTLY-yuga
```

**Comment by d4vidi** [comment]
Sorry, but history size is deeply essential for the effect to work.
The only advice I have is to try using an official CyanogenMod release (rather than a nightly build), or dump Cyanogen altogether.
