### ISSUE TITLE
ViewPager?

### ISSUE THREAD

**Issue by kyominoh** [EverythingMe/overscroll-decor#15]
Can you ever plan to be compatible support VIewPager?

**Comment by d4vidi** [comment]
Definitely. Supporting ViewPager essentially only requires writing a suitable adapter, as described in [the section on custom views](https://github.com/EverythingMe/overscroll-decor#custom-views).
As I won't seem to be getting to it anytime soon, I would highly appreciate a pull-request on your behalf.

**Comment by brucetoo** [comment]
check out ViewPager support  https://github.com/EverythingMe/overscroll-decor/pull/21

**Comment by d4vidi** [comment]
Fixed -- thanks @brucetoo
