### ISSUE TITLE
when scrollview's measure hight cannot fill whole screen, overscroll on textview or other widget not woking.

### ISSUE THREAD

**Issue by yanlusu** [EverythingMe/overscroll-decor#17]
step
1, fill layout xml using five linelayout, including in one linearlayout, wrapped by a scrollview;
2, but layout's height doesn't fill whole screen;
3, touch finger over linearlayout or other widget(space between widgets is woking well);
4, cannot scroll this UI;

**Comment by d4vidi** [comment]
Hi, thanks for this submission.
I'm not sure I understand the view hierarchy you're describing, would it be possible to get a screenshot of some sort?
Thanks

**Comment by d4vidi** [comment]
I believe this has been fixed - stay tuned for the newer lib version - 1.0.3 (current is 1.0.2).

**Comment by d4vidi** [comment]
Take another try with the new release - 1.0.3.
If problem isn't solved -- please resubmit.
Thanks!
