### ISSUE TITLE
Conflict with ListView onItemClick events

### ISSUE THREAD

**Issue by ZippoZeng** [EverythingMe/overscroll-decor#20]
Conflict with ListView onItemClick events

When I click on a item, this event will sometimes turn into a longclick event。

**Comment by Zippo1992** [comment]
sometime，i click item，but the event response onLongItemClick

**Comment by d4vidi** [comment]
There have been numerous issues with item selections. I'll try looking into it.
There's one thing I need to know, though: how do you register your item-click listeners?

**Comment by Zippo1992** [comment]
just like that.
`
       
         mRefreshLayout.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {

            @Override
            public void onRefresh() {

                if (mActivity != null) {
                    ((MainActivity) mActivity).pullData(false);
                }
            }

        });

        mListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {

            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                LogUtil.d(TAG, "onClickFrontView:" + position);
                Intent intent = new Intent(getActivity(), AddTaskActivity.class);
                intent.putExtra(Constants.EXTRA.TASK, mTaskModels.get(position));
                getActivity().startActivityForResult(intent, MainActivity.REQUEST_ADDTASK);
            }

        });

        mListView.setOnItemLongClickListener(new AdapterView.OnItemLongClickListener() {
                @Override
                public boolean onItemLongClick(AdapterView<?> parent, View view, final int position, long id) {
                    // ...
                    return true;
                }
            });`

**Comment by d4vidi** [comment]
Cool. Thanks for the info, I'll try my best looking into that real soon!

**Comment by ribbon-libs** [comment]
Hello guys,
Anything news of this issue? And is this project still supported?

Regards

**Comment by d4vidi** [comment]
Hi! I've made some updates that could get your problem fixed. Would appreciate it if you test the new version 1.0.4 out!

**Comment by vadol** [comment]
Hi ,In load more listview,last list item not clickable .
It is clickable if you double tap on list item
if 1 or 2 list item then not clickable list item in single time.

**Comment by vadol** [comment]
If use setOnItemLongClickListener then work properly but when over scroll list view performing ItemClickListernere after complete over scroll animation

**Comment by d4vidi** [comment]
Fixed in 1.0.4.
