### ISSUE TITLE
Overscroll effect does not work on ViewPager last page

### ISSUE THREAD

**Issue by martinconic** [EverythingMe/overscroll-decor#23]
Hi,

Thank you for adding overscroll to viewpager. 
I am having the issue with viewpager, that on the last page overscroll does not happen. Please can you help? I am trying to scroll from right to left and hopping to see an overscroll effect the right side of the last page.
Thank you.

**Comment by martinconic** [comment]
Can anyone help me with why bounce effect is not working on viewpager's last page?

**Comment by d4vidi** [comment]
This reminds me of issue #35: Are you using strictly full-screen view-pager pages?
