### ISSUE TITLE
Question: disable the listener/remove decor

### ISSUE THREAD

**Issue by Piuma37** [EverythingMe/overscroll-decor#27]
Is it possible to disable the overscroll listeners if not needed anymore? I've tried attatching a null recycler to the itemTouchHelper with no result.

**Comment by stefi92** [comment]
have you already solved this please?

**Comment by d4vidi** [comment]
Hi,
I'm not sure I understand the question very well. Are you referring to [over-scroll effect listeners](https://github.com/EverythingMe/overscroll-decor#over-scroll-listeners), or the [recycler-view's listeners for items swiping and dragging](https://github.com/EverythingMe/overscroll-decor#recyclerview-with-itemtouchhelper-based-swiping--dragging)?

The former can be removed by assigning `null`. As for the latter, I suppose the answer is *currently* no -- seeing that the concrete `ItemTouchHelper` isn't made available by my API.

**Comment by d4vidi** [comment]
@Piuma37 I'd be happy to assist if you'd be more specific as per my question from aug 19.
Thanks!
