### ISSUE TITLE
Overscroll effect not smooth as IOS

### ISSUE THREAD

**Issue by JitenNumberTank** [EverythingMe/overscroll-decor#28]
I have implement this project in my project. this is working in it. but gettng some issue with that. I have found Overscroll effect not smooth as IOS. and when I scroll listview at bottom overscroll then it top part comes over other view so its look like overlap view

**Comment by plastic-kai** [comment]
Same problem. Awsome project, but IOS looks much smoother.

**Comment by Paoneking** [comment]
use elevation

**Comment by JitenNumberTank** [comment]
Could you give me propercode for using elevation so I can use it in my ;project @Paoneking

**Comment by d4vidi** [comment]
This can be solved by placing the list-view as a child of a frame-layout. I've done so myself in the example project, e.g. with the vertical recycler view - you can use that for reference.
