### ISSUE TITLE
Back press programmatically is not working

### ISSUE THREAD

**Issue by parassftpl** [EverythingMe/overscroll-decor#29]
Below is my code inside fragment. I want to go back when overscroll threshold reaches 60. But it is getting count of backstack 0 and goes out of the Application. I am having only single fragment in before this. 

Below code is written in second fragment which is added in backstack. 

final MainActivity activity = (MainActivity) getActivity();

 IOverScrollDecor decor = OverScrollDecoratorHelper.setUpOverScroll(mScrollView);
        decor.setOverScrollUpdateListener(new IOverScrollUpdateListener() {
            @Override
            public void onOverScrollUpdate(IOverScrollDecor decor, int state, float offset) {
                if (((int) offset) > 60) {
                            activity.onBackPressed();
                }
            }
        });

**Comment by d4vidi** [comment]
First, I must point out that this is a very cool way to use listeners!
Second, I'd try digging deeper so as to see whether the offset indeed reaches 60 and `onBackPressed()` is in fact called.
In any case, I'd advise you not to use explicit integers - seeing that you might introduce different Ux on different devices. Instead, measure the total height/width and check for over-scrolling fraction compared to it (e.g. `offset/height > 0.2`).
