### ISSUE TITLE
why is my recyclerview doesnt overscroll when fast scrolling to top or bottom?

### ISSUE THREAD

**Issue by ohpoloha** [EverythingMe/overscroll-decor#33]
i do see the bounce effect if i hit the top or bottom then keep scrolling. 

but let's say if i try to scroll to top from the middle of the list. my recyclerview stops when it hits the first item. it doesnt do the overscroll effect. if i try to scroll more, then i see the effect. 

it's like scrolling fast to the top but suddenly stopped.  
is it by design? or i missed anything? 

all I did was just 

    new VerticalOverScrollBounceEffectDecorator(new RecyclerViewOverScrollDecorAdapter(recyclerView, callback));

**Comment by d4vidi** [comment]
Hi, please have a look at: https://github.com/EverythingMe/overscroll-decor/issues/1
Is this what you're referring to?

**Comment by ohpoloha** [comment]
thats right! i see. thanks.

**Comment by d4vidi** [comment]
Closing this then... thanks for the feedback tho
