### ISSUE TITLE
How to cancel the OverScrollDecoratorHelper.setUpStaticOverScroll effect when not needed?

### ISSUE THREAD

**Issue by ArsalanMaliks** [EverythingMe/overscroll-decor#34]
I have applied the lib and it works perfectly fine, now i have a case that i want to apply and cancel the effect manually can i achieve that?

**Comment by paour** [comment]
I have the same issue…

**Comment by d4vidi** [comment]
I'll work on a fix - should be pretty simple.

**Comment by d4vidi** [comment]
Feature is ready - will be included in my upcoming release.

**Comment by d4vidi** [comment]
Please try the associated feature support in the new 1.0.4 version: https://github.com/EverythingMe/overscroll-decor#dynamic-effect-disabling

**Comment by ArsalanMaliks** [comment]
Thank you so much for the solution.. it really worked
