### ISSUE TITLE
ViewPager OverScroll effect works on first element but not when moved to last element and back to first

### ISSUE THREAD

**Issue by jbmlaird** [EverythingMe/overscroll-decor#35]
A strange one. I have a ViewPager with 3 TextViews. The ViewPager moves between these three textviews but the width is such that you can see a preview of the next word. Each word is a different length.

The OverScroll works on the first element when scrolling to the left. If the user goes to the end of the ViewPager, the Overscroll works fine on the final element. But when returning to the first element, the overscroll no longer works. The ViewPager just won't scroll to the left anymore, as per normal ViewPager behaviour.

This does not happen when there are two elements. Only three elements.

I can confirm that this _does not happen_ when I am _not_ overriding getPageWidth() in the Adapter. How would I go about supporting this? The TextView is off the screen and destroyItem() is not being called even with setOffscreenPageLimit(0).

Here's the source code for that method:

```
        public float getPageWidth(int position)
        {
            if (position != 2)
            {
                viewHolders.get(position).fontText.measure(View.MeasureSpec.UNSPECIFIED, View.MeasureSpec.UNSPECIFIED);
                int deviceWidth = getResources().getDisplayMetrics().widthPixels;
                int textViewWidth = viewHolders.get(position).fontText.getMeasuredWidth();
                viewWidth = deviceWidth - textViewWidth;
                float widthPercentageWithoutMultiplication = ((float) viewWidth / deviceWidth);
                return 1 - widthPercentageWithoutMultiplication;
            }
            else
            {
                return super.getPageWidth(position);
            }
        }
```

The length in characters for the words is: 5, 9, 8. It's possible that having a very short first element, and therefore very short page width, is causing this issue?

**Comment by d4vidi** [comment]
I haven't taken a deep look into it but your code feels like it can't work with the way the over-scroll view-pager adapter is currently implemented. The reason is that the adapter relies on current page *scroll offset*; Possibly, fiddling with the page width may alter the attribute's behavior.

Before I deep-dive into things, allow me to suggest a different approach. Instead of overriding page width, apply negative values as page margins using `ViewPager.setPageMargins()`. If you nonetheless wish to create gaps between the pages, you can apply padding.

One last thing - could you provide a screenshot to clear things up?

**Comment by jbmlaird** [comment]
Thanks for coming back to me so fast. I initially used setPageMargins() to begin with, but this sets the page margins for every page, doesn't it? I want the margin for each page to change depending on the text length.

I created a new app just to display this behaviour and managed to narrow it down:

With the Strings TODAY, THURSDAY, FRIDAY and my custom text, normal behaviour happens.
With the Strings TODAY, WEDNESDAY, THURSDAY and default text, normal behaviour happens.
But with the Strings TODAY, WEDNESDAY, THURSDAY and my custom text, this is when the bug appears. 

So it might be a combination of the custom text being _slightly_ bigger and the longer string, as you can see more of the preview of Thursday with the default text.

Works fine with this text: 
![screenshot_20161026-121400](https://cloud.githubusercontent.com/assets/16595870/19724290/672bcd72-9b77-11e6-9da5-f2405ddf3a79.png)

Default text second page:
![screenshot_20161026-122855](https://cloud.githubusercontent.com/assets/16595870/19724417/e429c0b8-9b77-11e6-8acb-b2383129746e.png)

Custom first page:
![screenshot_20161026-121438](https://cloud.githubusercontent.com/assets/16595870/19724297/6ae9de0e-9b77-11e6-8125-6cb0d0d0e7e7.png)

second page:
![screenshot_20161026-122117](https://cloud.githubusercontent.com/assets/16595870/19724309/7299a18e-9b77-11e6-93f1-da25b541d4ab.png)

third page:
![screenshot_20161026-122121](https://cloud.githubusercontent.com/assets/16595870/19724312/765dc566-9b77-11e6-9068-a7d1a0be47d0.png)

**Comment by d4vidi** [comment]
You're right - indeed `setPageMargins` is not the way to go with this one.
May I make a small request then? Could you apply your example over the example project by forking it, so I could have a deeper look? It doesn't look like we're going to solve this issue without getting our hands dirty.

**Comment by d4vidi** [comment]
@jbmlaird I've take the liberty to try your code out myself, see how view-pager behaves in that scenario - and I have bad news. It looks as though view-pager mostly **misbehaves** in that case...
The current implementation relies heavily on the view-pager's `OnPageChangeListener` callback in monitoring real-time changes in view-pager scrolling. It works flawlessly when all page widths are 1, but in case some or even all are, say, 0.8, it fails miserably int reporting decent `position` and `offset` values to the callback's `onPageScrolled`. For example, in your case - when the last page is full-width and the rest are not, as the last page gets selected the callback's `onPageSelected` is called upon with position=2, and yet `onPageScrolled` is called with position=1 with unreasonable offsets.

I'm not sure there's a way to get that fixed out of the box. Perhaps there will be no choice (if any) and to override the view-pager and alter it more heavily.

**Comment by jbmlaird** [comment]
Sorry, had a busy weekend. Unfortunately, I thought that was gonna be the case :( 

Thanks for looking into this, appreciate it @d4vidi

**Comment by d4vidi** [comment]
Sure. I really hope to figure out a solution at some point but it's gonna be difficult.
Till then, I'm closing this as a "won't-fix"...
