### ISSUE TITLE
how to modify scroll speed  factor

### ISSUE THREAD

**Issue by Cornflower1991** [EverythingMe/overscroll-decor#36]
DEFAULT_TOUCH_DRAG_MOVE_RATIO_FWD ，DEFAULT_TOUCH_DRAG_MOVE_RATIO_BCK，DEFAULT_DECELERATE_FACTOR 。 i see this,

**Comment by d4vidi** [comment]
Have you tried: https://github.com/EverythingMe/overscroll-decor#effect-behavior-configuration
Specifically, refer to the first numeric argument.

**Comment by Cornflower1991** [comment]
ok thx
