### ISSUE TITLE
Can not work with SwipeRefresh

### ISSUE THREAD

**Issue by LxzBUG** [EverythingMe/overscroll-decor#37]
Can not work when recyclerView with SwipeRefresh  

and can not  use with Layout   

   LinearLayout llRootView=find...

 OverScrollDecoratorHelper.setUpStaticOverScroll(llRootView, OverScrollDecoratorHelper.ORIENTATION_VERTICAL);

can not

**Comment by d4vidi** [comment]
Swipe-to-refresh: duplicate of issue #5.
Linear-layout can't work cause it's not scrollable...
