### ISSUE TITLE
how to let top can overscroll,bottom can't

### ISSUE THREAD

**Issue by neuyu** [EverythingMe/overscroll-decor#39]
i want to let my scrollview could overscroll from the top ,but bottom couldn't

**Comment by Haoxiqiang** [comment]
try use https://github.com/EverythingMe/overscroll-decor#advanced-usage
``` 
@Override
public boolean isInAbsoluteEnd() {
    return false;
}
```

**Comment by d4vidi** [comment]
@Haoxiqiang Thanks :-)
