### ISSUE TITLE
minSdkVersion 16

### ISSUE THREAD

**Issue by hrules6872** [EverythingMe/overscroll-decor#4]
Is there any reason for using minSdkVersion 16? Is it not working with lower versions?

**Comment by d4vidi** [comment]
Hey there, Chances are that it can work with lower version -- I'll have to look into that and let you know.
Thanks for the submission!

**Comment by NitroXenon** [comment]
Really want this works with API 14 :D

**Comment by AndreiD** [comment]
up+

**Comment by suntao2yl** [comment]
Really want this works with API 15 :D

**Comment by d4vidi** [comment]
All, thanks for the feedback. There are a number of pending modifications for this library which I hope to release within weeks. I'll do my best to include API support enhancement as requested. Please stay tuned!

**Comment by d4vidi** [comment]
Changed min SDK to 14 in new 1.0.1 release.
