### ISSUE TITLE
Cannot scroll for webview

### ISSUE THREAD

**Issue by JimmyNi** [EverythingMe/overscroll-decor#41]
Do have the over-scroll effect but cannot scroll to the bottom for the web page. Pls help here.

**Comment by JimmyNi** [comment]
I have fix the issue from the link below [http://stackoverflow.com/a/33960629/4860612](url)

**Comment by d4vidi** [comment]
Hi @JimmyNi, have you tried applying the suggest code from stackoverflow.com?

**Comment by JimmyNi** [comment]
Yes, it worked, and I also found out that you are the author of the correct answer, thanks a lot:)
