### ISSUE TITLE
SwipeRefresh Issue

### ISSUE THREAD

**Issue by bahacan19** [EverythingMe/overscroll-decor#5]
How can i use this class with [this Google's SwipeRefreshLayout] (http://developer.android.com/training/swipe/add-swipe-interface.html)

**Comment by d4vidi** [comment]
Support in Google's swipe-to-refresh hasn't been tested out yet. Have you tried it? What are the problems that you come across?

Thanks.

**Comment by SasanFarrokh** [comment]
Can't use swipe-to-refresh layout , it does not call the event.
but can set a overscroll listener and apply the refresh manually
