### ISSUE TITLE
selector  status

### ISSUE THREAD

**Issue by kaku2015** [EverythingMe/overscroll-decor#6]
How  cacel pressing drawable when overScrollingState of use in ListView.

**Comment by d4vidi** [comment]
Could you please elaborate and perhaps attach some screenshots?
Also, try the new 1.0.1 release to see if the problem is solved.

**Comment by kaku2015** [comment]
### The screenshots When reaching the top to pull down
![image](https://github.com/kaku2015/WeatherChartView/blob/master/sample/issues_screeshots/1.png)
![image](https://github.com/kaku2015/WeatherChartView/blob/master/sample/issues_screeshots/2.png)

### One more question：
### When the bottom continues to pull up the contents will exceed the range of ListView
![image](https://github.com/kaku2015/WeatherChartView/blob/master/sample/issues_screeshots/3.png)
![image](https://github.com/kaku2015/WeatherChartView/blob/master/sample/issues_screeshots/4.png)

I'm sorry for my English...

Thanks!

**Comment by kaku2015** [comment]
Picture shows a problem please click on the link below

[](https://github.com/kaku2015/WeatherChartView/tree/master/sample/issues_screeshots)

**Comment by kaku2015** [comment]
Picture shows a problem please click on the link below.

https://github.com/kaku2015/WeatherChartView/tree/master/sample/issues_screeshots

**Comment by d4vidi** [comment]
Hey @kaku2015, is this issue still in effect with the most recent effect lib version (1.0.1)?
