### ISSUE TITLE
Sensitivity

### ISSUE THREAD

**Issue by Mr-GX** [EverythingMe/overscroll-decor#7]
How to control sensitivity slide?

**Comment by d4vidi** [comment]
Hi! Please try referring to https://github.com/EverythingMe/overscroll-decor#effect-behavior-configuration.

**Comment by Mr-GX** [comment]
@d4vidi  thank you for your reply,I did not notice that.

**Comment by d4vidi** [comment]
No sweat. Please let me know if it works for ya.
