### ISSUE TITLE
Add ability to disable overscroll from the one side

### ISSUE THREAD

**Issue by suhocki** [EverythingMe/overscroll-decor#71]
Please add a functionality to disable overscroll from one side, e.g. I want to make user to see overscroll from the top but not from the bottom

**Comment by d4vidi** [comment]
This is already supported. Simply override the existing adapter that suites your needs, and have `isInAbsoluteEnd()` always return false (use [this](https://github.com/EverythingMe/overscroll-decor#custom-views) as a reference).
