### ISSUE TITLE
Feature request: overscroll listener

### ISSUE THREAD

**Issue by duckinferno** [EverythingMe/overscroll-decor#8]
It'd be great to have some kind of onOverScrolled(float) listener, which accurately calls the overscroll amount whenever it occurs.  

I've currently hooked into translateView(), but this does not get called when the view is settling back into place.  Hooking into the settling animation doesn't seem possible externally.

My use case: having views react to a RecyclerView's overscroll and transform in various ways, and reverse these transformations when the overscroll touch is released.  I'm sure there are many others :)

**Comment by d4vidi** [comment]
Hey,
thanks for this feedback!
It so happens that I've been planning on introducing such a listener for a while now -- but haven't done so yet since no requests have been made on such a feature.
So basically I'd like to thank you for putting interest into it! I now how proper motivation to implement that :-)

**Comment by andanicalik** [comment]
Hey,
Are there any progress about overscroll's offset listener ?
Thanks for library. Have a good day.

**Comment by d4vidi** [comment]
Hi,
haven't got to it yet, I'm afraid. Hoping to get to it real soon.
BTW do you have an idea as to what kind of a callback you would find most useful?

**Comment by XavierSAndroid** [comment]
@duckinferno cuz both the realization of translation and bounce-back anmation are based on `View.setTranslationX(float)` or `View.setTranslationY(float)`, you could override that method of your view, and will get the value of overscroll either on touch-scroll or on animating.

**Comment by andanicalik** [comment]
Hi,
Firstly, thanks for your interest. I think that the callback should return position(top, right, bottom, left), offset and view.

**Comment by d4vidi** [comment]
Sure. Always happy to get feedbacks.
@XavierSAndroid good call, that could work as an intermediate solution.
@andanicalik Not sure I follow. By 'position' - you're referring to the view's absolute position? if so, that can be retrieved from the view itself. As for the offset - I agree: offset in pixels; could also be used for computing as a ratio (value in (0..1]) compared to the scrollable view's total height, if needed.
I'm also thinking about adding the 'state' -- scrolled start / scroll in-progress / bouncing-back / scroll-ended.

**Comment by andanicalik** [comment]
By 'position', I want to refer bouncing position. It can be top-end of list if it's vertical, also left-right of list if it's horizontal, not view absolute position. Sorry for misunderstanding.

**Comment by duckinferno** [comment]
@Xavier yeah that's my interim solution too ☺

**Comment by d4vidi** [comment]
Featured added to new version - 1.0.2.
Feedbacks would be appreciated!
