### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by ilyassesalama** [EverythingMe/overscroll-decor#80]
When over scrolling from bottom using RecyclerView or ScrollView, the content shows above the first layout (I'm not good at explaining, but the image is enough to explain the issue)
![IMG_20210212_045928](https://user-images.githubusercontent.com/46769766/107728831-71f81780-6cef-11eb-8655-cddc9f300c50.jpg)

**Comment by Krupson** [comment]
You should rearrange views in your XML layout file. Views declared on top of file are "overlayed" by the views declared at the bottom. Simply move RecyclerView declaration to be before the declaration of the search view.

**Comment by d4vidi** [comment]
Also, `android:clipChildren` may [come in handy](https://stackoverflow.com/questions/25044085/when-drawing-outside-the-view-clip-bounds-with-android-how-do-i-prevent-underli).
