### ISSUE TITLE
Migrate repository from jcenter

### ISSUE THREAD

**Issue by Krupson** [EverythingMe/overscroll-decor#81]
As bintray announced ( https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ ) jcenter repository will not be available anymore, so please move the library somewhere else.

**Comment by d4vidi** [comment]
Will do - thank you!

**Comment by d4vidi** [comment]
https://issues.sonatype.org/browse/OSSRH-67690

**Comment by d4vidi** [comment]
Library is now available as the following artifact under maven-central:
```
implementation 'io.github.everythingme:overscroll-decor-android:1.1.1'
```
